version: '3.8'
services: 
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: topicapp 
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./pgdata/init.sql:/docker-entrypoint-initdb.d/initial_config.sql
    ports:
      - '1000:5432'
  app:
    container_name: topicapp
    build:
      context: ./
      target: production
    image: topicapp:1.0
    depends_on:
      - postgres
    ports:
      - '5000:8080'
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 1000
      DB_USER: developer
      DB_PASSWORD: supermanisdead
      DB_NAME: topicapp
    links:
      - postgres
    volumes:
      - ./:/src
      - /src/node_modules
volumes:
  postgres: 
    driver: local